build.gradle
src/main/java/com/supercoding/shoppingmallbackend/common/util/DateUtils.java
src/main/java/com/supercoding/shoppingmallbackend/config/JasyptConfig.java
src/main/java/com/supercoding/shoppingmallbackend/entity/Address.java
src/main/java/com/supercoding/shoppingmallbackend/entity/Answer.java
src/main/java/com/supercoding/shoppingmallbackend/entity/Category.java
src/main/java/com/supercoding/shoppingmallbackend/entity/CommonField.java
src/main/java/com/supercoding/shoppingmallbackend/entity/Consumer.java
src/main/java/com/supercoding/shoppingmallbackend/entity/Genre.java
src/main/java/com/supercoding/shoppingmallbackend/entity/Product.java
src/main/java/com/supercoding/shoppingmallbackend/entity/ProductCategory.java
src/main/java/com/supercoding/shoppingmallbackend/entity/ProductContentImage.java
src/main/java/com/supercoding/shoppingmallbackend/entity/Profile.java
src/main/java/com/supercoding/shoppingmallbackend/entity/PurchaseHistory.java
src/main/java/com/supercoding/shoppingmallbackend/entity/Question.java
src/main/java/com/supercoding/shoppingmallbackend/entity/Review.java
src/main/java/com/supercoding/shoppingmallbackend/entity/Role.java
src/main/java/com/supercoding/shoppingmallbackend/entity/ScrapList.java
src/main/java/com/supercoding/shoppingmallbackend/entity/Seller.java
src/main/java/com/supercoding/shoppingmallbackend/entity/ShoppingCart.java
src/main/java/com/supercoding/shoppingmallbackend/service/ExampleService.java
src/main/resources/application.yml

엔티티 생성과 db연결, grdle에 jpa, jdbc 추가

엔티티생성, db연결(암호화)

---

src/main/java/com/supercoding/shoppingmallbackend/common/CommonResponse.java
src/main/java/com/supercoding/shoppingmallbackend/common/util/ApiUtils.java
src/main/java/com/supercoding/shoppingmallbackend/controller/aop/LoggingAspect.java

공통 응답 status: {} => status: code 로 수정

---

src/main/java/com/supercoding/shoppingmallbackend/common/Error/CustomException.java
src/main/java/com/supercoding/shoppingmallbackend/common/Error/domain/UserErrorCode.java
src/main/java/com/supercoding/shoppingmallbackend/controller/OrderController.java
src/main/java/com/supercoding/shoppingmallbackend/entity/PurchaseHistory.java
src/main/java/com/supercoding/shoppingmallbackend/entity/ShoppingCart.java
src/main/java/com/supercoding/shoppingmallbackend/repository/OrderRepository.java
src/main/java/com/supercoding/shoppingmallbackend/service/OrderService.java

장바구니, 결제내역 엔티티 수정

---

src/main/java/com/supercoding/shoppingmallbackend/controller/ShoppingCartController.java
src/main/java/com/supercoding/shoppingmallbackend/dto/response/ShoppingCartItemResponse.java

Refactor: ShoppingController 더미 코드와 실제 서비스 코드 쉽게 스위칭되도록 개선

Refactor: ShoppingController 더미 코드와 실제 서비스 코드 쉽게 스위칭되도록 개선

---

src/main/java/com/supercoding/shoppingmallbackend/common/Error/domain/GenreErrorCode.java
src/main/java/com/supercoding/shoppingmallbackend/common/util/DateUtils.java
src/main/java/com/supercoding/shoppingmallbackend/controller/ShoppingCartController.java
src/main/java/com/supercoding/shoppingmallbackend/dto/response/ProductDetailResponse.java
src/main/java/com/supercoding/shoppingmallbackend/dto/response/ProductInCartResponse.java
src/main/java/com/supercoding/shoppingmallbackend/dto/response/ShoppingCartItemResponse.java
src/main/java/com/supercoding/shoppingmallbackend/repository/GenreRepository.java
src/main/java/com/supercoding/shoppingmallbackend/service/ShoppingCartService.java

Genre 관련 클래스 추가, 장바구니 서비스 로직 수정, ProductDetailResponse에 from 메서드 추가

Genre 관련 클래스 추가, 장바구니 서비스 로직 수정, ProductDetailResponse 확장

---

src/main/java/com/supercoding/shoppingmallbackend/entity/Payment.java

payments 엔티티 seller 필드 제거

---

src/main/java/com/supercoding/shoppingmallbackend/controller/PaymentsController.java
src/main/java/com/supercoding/shoppingmallbackend/dto/response/ConsumerResponse.java
src/main/java/com/supercoding/shoppingmallbackend/dto/response/ProductSimpleResponse.java
src/main/java/com/supercoding/shoppingmallbackend/dto/response/SaleResponse.java
src/main/java/com/supercoding/shoppingmallbackend/dto/response/ShoppingCartItemResponse.java
src/main/java/com/supercoding/shoppingmallbackend/repository/PaymentRepository.java
src/main/java/com/supercoding/shoppingmallbackend/service/PaymentService.java

구매내역 조회, 판매내역 조회 기능 구현

---

src/main/java/com/supercoding/shoppingmallbackend/dto/response/ShoppingCartItemResponse.java
src/main/java/com/supercoding/shoppingmallbackend/repository/ConsumerRepository.java
src/main/java/com/supercoding/shoppingmallbackend/repository/ProductRepository.java
src/main/java/com/supercoding/shoppingmallbackend/repository/ShoppingCartRepository.java
src/main/java/com/supercoding/shoppingmallbackend/service/ShoppingCartService.java

장바구니 서비스 로직, 리포지토리 로직 개선

---

src/main/java/com/supercoding/shoppingmallbackend/controller/ShoppingCartController.java
src/main/java/com/supercoding/shoppingmallbackend/dto/request/ShoppingCartItemRequest.java
src/main/java/com/supercoding/shoppingmallbackend/dto/response/ShoppingCartItemResponse.java
src/main/java/com/supercoding/shoppingmallbackend/repository/ConsumerRepository.java
src/main/java/com/supercoding/shoppingmallbackend/repository/ProductRepository.java
src/main/java/com/supercoding/shoppingmallbackend/repository/ShoppingCartRepository.java

JPQL limit 절 제거, Swagger 작업

---

src/main/java/com/supercoding/shoppingmallbackend/controller/PaymentsController.java
src/main/java/com/supercoding/shoppingmallbackend/dto/response/PaymentResponse.java

Swagger 작업 중

---

src/main/java/com/supercoding/shoppingmallbackend/common/CommonResponse.java

공통응답에 Swagger 작업

---

src/main/java/com/supercoding/shoppingmallbackend/controller/ShoppingCartController.java
src/main/java/com/supercoding/shoppingmallbackend/dto/request/PaymentRequest.java
src/main/java/com/supercoding/shoppingmallbackend/dto/request/ShoppingCartItemRequest.java
src/main/java/com/supercoding/shoppingmallbackend/dto/response/ConsumerResponse.java
src/main/java/com/supercoding/shoppingmallbackend/dto/response/PaymentResponse.java
src/main/java/com/supercoding/shoppingmallbackend/dto/response/ProductSimpleResponse.java
src/main/java/com/supercoding/shoppingmallbackend/dto/response/PurchaseResponse.java
src/main/java/com/supercoding/shoppingmallbackend/dto/response/SaleResponse.java
src/main/java/com/supercoding/shoppingmallbackend/dto/response/ShoppingCartItemResponse.java

장바구니, 결제내역 swagger 작업 완

---

src/main/java/com/supercoding/shoppingmallbackend/controller/ShoppingCartController.java
src/main/java/com/supercoding/shoppingmallbackend/repository/ConsumerRepository.java
src/main/java/com/supercoding/shoppingmallbackend/repository/SellerRepository.java
src/main/java/com/supercoding/shoppingmallbackend/service/PaymentService.java
src/main/java/com/supercoding/shoppingmallbackend/service/ShoppingCartService.java

인증된 회원 정보로 구매자 판매자 조회하도록 구현

---

src/main/java/com/supercoding/shoppingmallbackend/common/Error/domain/PaymentErrorCode.java
src/main/java/com/supercoding/shoppingmallbackend/common/Error/domain/ShoppingCartErrorCode.java
src/main/java/com/supercoding/shoppingmallbackend/controller/ShoppingCartController.java
src/main/java/com/supercoding/shoppingmallbackend/entity/Payment.java
src/main/java/com/supercoding/shoppingmallbackend/repository/PaymentRepository.java
src/main/java/com/supercoding/shoppingmallbackend/service/PaymentService.java
src/main/java/com/supercoding/shoppingmallbackend/service/ShoppingCartService.java

장바구니, 결제 기능 구현 완료

---

src/main/java/com/supercoding/shoppingmallbackend/controller/ShoppingCartController.java
src/main/java/com/supercoding/shoppingmallbackend/dto/request/ShoppingCartIdSetRepuest.java
src/main/java/com/supercoding/shoppingmallbackend/service/ShoppingCartService.java

장바구니 선택 삭제 기능 구현

---

src/main/java/com/supercoding/shoppingmallbackend/controller/ShoppingCartController.java
src/main/java/com/supercoding/shoppingmallbackend/dto/request/ShoppingCartIdSetRepuest.java

간단한 Swagger 작업

---

src/main/java/com/supercoding/shoppingmallbackend/common/Error/domain/CommonErrorCode.java
src/main/java/com/supercoding/shoppingmallbackend/controller/ShoppingCartController.java
src/main/java/com/supercoding/shoppingmallbackend/dto/response/PaginationResponse.java
src/main/java/com/supercoding/shoppingmallbackend/repository/ShoppingCartRepository.java
src/main/java/com/supercoding/shoppingmallbackend/service/ShoppingCartService.java

장바구니 pagination으로 조회 구현!

---

src/main/java/com/supercoding/shoppingmallbackend/controller/PaymentsController.java
src/main/java/com/supercoding/shoppingmallbackend/controller/ShoppingCartController.java
src/main/java/com/supercoding/shoppingmallbackend/repository/PaymentRepository.java
src/main/java/com/supercoding/shoppingmallbackend/service/PaymentService.java
src/main/java/com/supercoding/shoppingmallbackend/service/ShoppingCartService.java

구매내역 조회, 판매내역 조회 pagination 구현

구매내역 조회, 판매내역 조회 pagination 구현

---

src/main/java/com/supercoding/shoppingmallbackend/controller/PaymentsController.java
src/main/java/com/supercoding/shoppingmallbackend/controller/ShoppingCartController.java

토큰 받는 Swagger 어노테이션 제거

---

src/main/java/com/supercoding/shoppingmallbackend/controller/ShoppingCartController.java
src/main/java/com/supercoding/shoppingmallbackend/service/ShoppingCartService.java

null을 반환하지 않도록 수정

---

src/main/java/com/supercoding/shoppingmallbackend/controller/PaymentsController.java
src/main/java/com/supercoding/shoppingmallbackend/service/PaymentService.java
src/main/java/com/supercoding/shoppingmallbackend/service/ProfileService.java

장바구니 선택 구매 기능 구현

---

src/main/java/com/supercoding/shoppingmallbackend/controller/ShoppingCartController.java
src/main/java/com/supercoding/shoppingmallbackend/dto/request/ListRequest.java
src/main/java/com/supercoding/shoppingmallbackend/dto/response/ShoppingCartItemResponse.java
src/main/java/com/supercoding/shoppingmallbackend/service/ShoppingCartService.java

장바구니에 여러 상품 한번에 추가 및 수량 변경 기능 추가

장바구니에 여러 상품 한번에 추가 및 수량 변경 기능 추가

---

src/main/java/com/supercoding/shoppingmallbackend/common/Error/domain/UtilErrorCode.java
src/main/java/com/supercoding/shoppingmallbackend/common/util/FilePath.java
src/main/java/com/supercoding/shoppingmallbackend/controller/ReviewController.java
src/main/java/com/supercoding/shoppingmallbackend/dto/request/ReviewRequest.java
src/main/java/com/supercoding/shoppingmallbackend/dto/response/ConsumerDetailResponse.java
src/main/java/com/supercoding/shoppingmallbackend/dto/response/ProfileResponse.java
src/main/java/com/supercoding/shoppingmallbackend/dto/response/ReviewResponse.java
src/main/java/com/supercoding/shoppingmallbackend/entity/Review.java
src/main/java/com/supercoding/shoppingmallbackend/repository/ReviewRepository.java
src/main/java/com/supercoding/shoppingmallbackend/service/ReviewService.java

리뷰 작성 기능 구현

---

src/main/java/com/supercoding/shoppingmallbackend/controller/ReviewController.java
src/main/java/com/supercoding/shoppingmallbackend/dto/request/ReviewRequest.java
src/main/java/com/supercoding/shoppingmallbackend/service/ReviewService.java

리뷰 작성 기능 버그 수정

---

src/main/java/com/supercoding/shoppingmallbackend/controller/ReviewController.java
src/main/java/com/supercoding/shoppingmallbackend/service/ReviewService.java

리뷰 작성 버그 수정

---

src/main/java/com/supercoding/shoppingmallbackend/controller/ReviewController.java
src/main/java/com/supercoding/shoppingmallbackend/entity/Review.java
src/main/java/com/supercoding/shoppingmallbackend/repository/ReviewRepository.java
src/main/java/com/supercoding/shoppingmallbackend/service/ReviewService.java

상품 리뷰 조회 기능 구현

---

src/main/java/com/supercoding/shoppingmallbackend/controller/ReviewController.java
src/main/java/com/supercoding/shoppingmallbackend/repository/ReviewRepository.java
src/main/java/com/supercoding/shoppingmallbackend/service/ReviewService.java

내가 작성한 리뷰 조회 기능 추가

---

src/main/java/com/supercoding/shoppingmallbackend/common/Error/domain/CommonErrorCode.java
src/main/java/com/supercoding/shoppingmallbackend/controller/PaymentsController.java
src/main/java/com/supercoding/shoppingmallbackend/controller/ReviewController.java
src/main/java/com/supercoding/shoppingmallbackend/controller/ShoppingCartController.java
src/main/java/com/supercoding/shoppingmallbackend/dto/response/PaginationPageResponse.java
src/main/java/com/supercoding/shoppingmallbackend/dto/response/PaginationSliceResponse.java
src/main/java/com/supercoding/shoppingmallbackend/entity/Consumer.java
src/main/java/com/supercoding/shoppingmallbackend/entity/Review.java
src/main/java/com/supercoding/shoppingmallbackend/entity/ShoppingCart.java
src/main/java/com/supercoding/shoppingmallbackend/repository/ReviewRepository.java
src/main/java/com/supercoding/shoppingmallbackend/service/PaymentService.java
src/main/java/com/supercoding/shoppingmallbackend/service/ReviewService.java
src/main/java/com/supercoding/shoppingmallbackend/service/ShoppingCartService.java

상품 리뷰 페이지네이션 조회 구현

---

src/main/java/com/supercoding/shoppingmallbackend/controller/ReviewController.java
src/main/java/com/supercoding/shoppingmallbackend/repository/ReviewRepository.java
src/main/java/com/supercoding/shoppingmallbackend/service/ReviewService.java

내가 작성한 리뷰 페이지네이션 조회 기능 구현

---

src/main/java/com/supercoding/shoppingmallbackend/controller/ReviewController.java
src/main/java/com/supercoding/shoppingmallbackend/service/ReviewService.java

리뷰 삭제 기능 구현

---

src/main/java/com/supercoding/shoppingmallbackend/common/Error/domain/ReviewErrorCode.java
src/main/java/com/supercoding/shoppingmallbackend/controller/ReviewController.java
src/main/java/com/supercoding/shoppingmallbackend/repository/ReviewRepository.java
src/main/java/com/supercoding/shoppingmallbackend/service/ReviewService.java

리뷰 수정 기능 구현

---

src/main/java/com/supercoding/shoppingmallbackend/controller/ScrapController.java
src/main/java/com/supercoding/shoppingmallbackend/service/ScrapService.java

찜 취소 기능 구현

---

src/main/java/com/supercoding/shoppingmallbackend/controller/ProductController.java
src/main/java/com/supercoding/shoppingmallbackend/dto/request/ProductFileRequest.java
src/main/java/com/supercoding/shoppingmallbackend/entity/Product.java
src/main/java/com/supercoding/shoppingmallbackend/repository/CategoryRepository.java
src/main/java/com/supercoding/shoppingmallbackend/repository/ProductCategoryRepository.java
src/main/java/com/supercoding/shoppingmallbackend/service/ProductService.java

Feat: 상품 수정 이미지 제외 개발 완료

---

src/main/java/com/supercoding/shoppingmallbackend/controller/AnswerController.java
src/main/java/com/supercoding/shoppingmallbackend/controller/QuestionController.java

refactor : ApiOpertion 추가

---

src/main/java/com/supercoding/shoppingmallbackend/common/Error/domain/OrderByErrorCode.java
src/main/java/com/supercoding/shoppingmallbackend/common/Error/domain/ReviewErrorCode.java
src/main/java/com/supercoding/shoppingmallbackend/controller/ReviewController.java
src/main/java/com/supercoding/shoppingmallbackend/controller/ShoppingCartController.java
src/main/java/com/supercoding/shoppingmallbackend/entity/sortProperty/ReviewSortProperty.java
src/main/java/com/supercoding/shoppingmallbackend/repository/ProductRepository.java
src/main/java/com/supercoding/shoppingmallbackend/repository/ReviewRepository.java
src/main/java/com/supercoding/shoppingmallbackend/repository/ScrapRepository.java
src/main/java/com/supercoding/shoppingmallbackend/repository/ShoppingCartRepository.java
src/main/java/com/supercoding/shoppingmallbackend/service/ReviewService.java
src/main/java/com/supercoding/shoppingmallbackend/service/ScrapService.java
src/main/java/com/supercoding/shoppingmallbackend/service/ShoppingCartService.java

상품 리뷰 조회 정렬 기능 추가 및 코드 리팩토링

---

src/main/java/com/supercoding/shoppingmallbackend/dto/response/ConsumerSimpleResponse.java
src/main/java/com/supercoding/shoppingmallbackend/dto/response/ProductSimpleResponse.java
src/main/java/com/supercoding/shoppingmallbackend/dto/response/ReviewResponse.java

리뷰 정보에 간단한 구매자와 상품 정보만 담길 수 있도록 개선

리뷰 정보에 간단한 구매자와 상품 정보만 담길 수 있도록 개선

---

src/main/java/com/supercoding/shoppingmallbackend/dto/response/ProductResponse.java
src/main/java/com/supercoding/shoppingmallbackend/dto/response/ShoppingCartItemResponse.java
src/main/java/com/supercoding/shoppingmallbackend/repository/ReviewRepository.java
src/main/java/com/supercoding/shoppingmallbackend/repository/ScrapRepository.java
src/main/java/com/supercoding/shoppingmallbackend/repository/ShoppingCartRepository.java
src/main/java/com/supercoding/shoppingmallbackend/service/PaymentService.java
src/main/java/com/supercoding/shoppingmallbackend/service/ReviewService.java
src/main/java/com/supercoding/shoppingmallbackend/service/ScrapService.java
src/main/java/com/supercoding/shoppingmallbackend/service/ShoppingCartService.java

장바구니, 리뷰, 찜목록 조회시 최근순으로 정렬되도록 개선

장바구니, 리뷰, 찜목록 조회시 최근순으로 정렬되도록 개선

---

src/main/java/com/supercoding/shoppingmallbackend/common/Error/domain/ShoppingCartErrorCode.java
src/main/java/com/supercoding/shoppingmallbackend/service/ReviewService.java
src/main/java/com/supercoding/shoppingmallbackend/service/ShoppingCartService.java

RESTfull한 에러코드를 주기 위해 코드 개선

---

src/main/java/com/supercoding/shoppingmallbackend/common/util/PaginationBuilder.java
src/main/java/com/supercoding/shoppingmallbackend/controller/ProductController.java
src/main/java/com/supercoding/shoppingmallbackend/dto/response/PaginationResponse.java
src/main/java/com/supercoding/shoppingmallbackend/dto/response/ProductDetailResponse.java
src/main/java/com/supercoding/shoppingmallbackend/dto/response/ProductListResponse.java
src/main/java/com/supercoding/shoppingmallbackend/entity/Product.java
src/main/java/com/supercoding/shoppingmallbackend/repository/ProductRepository.java
src/main/java/com/supercoding/shoppingmallbackend/service/PaymentService.java
src/main/java/com/supercoding/shoppingmallbackend/service/ProductService.java
src/main/java/com/supercoding/shoppingmallbackend/service/ReviewService.java
src/main/java/com/supercoding/shoppingmallbackend/service/ScrapService.java
src/main/java/com/supercoding/shoppingmallbackend/service/ShoppingCartService.java

Feature/상품/상품조회 평균별점

---

src/main/java/com/supercoding/shoppingmallbackend/common/Error/domain/PaymentErrorCode.java
src/main/java/com/supercoding/shoppingmallbackend/common/Error/domain/SellerErrorCode.java
src/main/java/com/supercoding/shoppingmallbackend/controller/PaymentsController.java
src/main/java/com/supercoding/shoppingmallbackend/dto/response/PurchaseResponse.java
src/main/java/com/supercoding/shoppingmallbackend/entity/Seller.java
src/main/java/com/supercoding/shoppingmallbackend/repository/ConsumerRepository.java
src/main/java/com/supercoding/shoppingmallbackend/repository/PaymentRepository.java
src/main/java/com/supercoding/shoppingmallbackend/repository/SellerRepository.java
src/main/java/com/supercoding/shoppingmallbackend/service/PaymentService.java
src/main/java/com/supercoding/shoppingmallbackend/service/ReviewService.java
src/main/java/com/supercoding/shoppingmallbackend/service/ScrapService.java
src/main/java/com/supercoding/shoppingmallbackend/service/ShoppingCartService.java

결제내역 관련 코드 개선

---

src/main/java/com/supercoding/shoppingmallbackend/common/util/PaginationBuilder.java
src/main/java/com/supercoding/shoppingmallbackend/dto/response/PaginationResponse.java

PaginationResponse 필드 순서 변경

---

src/main/java/com/supercoding/shoppingmallbackend/dto/response/profile/ProfileInfoResponse.java
src/main/java/com/supercoding/shoppingmallbackend/service/ProfileService.java

Refactor: 유저 정보 조회 시 주소 정보 반환

---

src/main/java/com/supercoding/shoppingmallbackend/controller/PaymentsController.java
src/main/java/com/supercoding/shoppingmallbackend/dto/response/PaymentResponse.java
src/main/java/com/supercoding/shoppingmallbackend/dto/response/PurchaseResponse.java
src/main/java/com/supercoding/shoppingmallbackend/dto/response/SaleResponse.java
src/main/java/com/supercoding/shoppingmallbackend/repository/PaymentRepository.java
src/main/java/com/supercoding/shoppingmallbackend/service/PaymentService.java

장바구니 결제해도 응답에서 안 사라지던 버그 수정, 구매내역 및 판매내역 주문번호 조회 시 pagination 가능하도록 구현

장바구니 결제해도 응답에서 안 사라지던 버그 수정, 구매내역 및 판매내역 주문번호 조회 시 pagination 가능하도록 구현

---

src/main/java/com/supercoding/shoppingmallbackend/security/AuthenticationConfig.java

장바구니, 판매내역, 리뷰, 찜 목록에 Spring Security 적용되도록 등록

장바구니, 판매내역, 리뷰, 찜 목록에 Spring Security 적용되도록 등록

---

src/main/java/com/supercoding/shoppingmallbackend/controller/ProfileController.java
src/main/java/com/supercoding/shoppingmallbackend/dto/response/oauth/KakaoApiClient.java
src/main/java/com/supercoding/shoppingmallbackend/security/EndExceptionHandler.java

refactor: oauth redirect 경로 프론트 협의 후 변경

---

src/main/java/com/supercoding/shoppingmallbackend/service/PaymentService.java

상품 구매시 판매내역 캐시 초기화 안 되던 버그 수정
